"""
DomainAtlas - Scan History Service

Handles persistent storage and retrieval of completed
DomainAtlas scan results.

History is stored as JSON snapshots under:

    data/history/
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


# ============================================================
# HISTORY DIRECTORY
# ============================================================

# Project root:
# backend/services/history_service.py
#       ↑
# parents[0] = services
# parents[1] = backend
# parents[2] = DomainAtlas
PROJECT_ROOT = Path(__file__).resolve().parents[2]

HISTORY_DIR = PROJECT_ROOT / "data" / "history"

# Make sure the directory exists.
HISTORY_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# JSON SERIALIZATION
# ============================================================

def _make_json_safe(value: Any) -> Any:
    """
    Convert values into JSON-serializable structures.

    This protects history saving from unexpected objects such as:
    sets, tuples, Path objects, or other non-standard values.
    """

    if value is None:
        return None

    if isinstance(value, (str, int, float, bool)):
        return value

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, datetime):
        return value.isoformat()

    if isinstance(value, dict):
        return {
            str(key): _make_json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        return [
            _make_json_safe(item)
            for item in value
        ]

    # Last-resort conversion for unexpected objects.
    return str(value)


# ============================================================
# FILE PATH
# ============================================================

def _history_file(scan_id: str) -> Path:
    """
    Return the JSON file path for a scan.
    """

    # Keep the scan ID filename-safe.
    safe_scan_id = "".join(
        character
        for character in str(scan_id)
        if character.isalnum()
        or character in ("-", "_")
    )

    if not safe_scan_id:
        raise ValueError("Invalid scan ID.")

    return HISTORY_DIR / f"scan_{safe_scan_id}.json"


# ============================================================
# SAVE SCAN
# ============================================================

def save_scan(
    scan_id: str,
    result: Dict[str, Any],
    started_at: Optional[str] = None,
    completed_at: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Save a completed DomainAtlas scan as a persistent JSON snapshot.

    Parameters
    ----------
    scan_id:
        Unique scan identifier generated by the backend.

    result:
        Final scan result produced by the pipeline/main API flow.

    started_at:
        Optional ISO timestamp for when the scan started.

    completed_at:
        Optional ISO timestamp for when the scan completed.

    Returns
    -------
    dict
        Metadata about the saved history entry.
    """

    if not scan_id:
        raise ValueError("scan_id is required.")

    if not isinstance(result, dict):
        raise TypeError("result must be a dictionary.")

    # Use supplied completion time or generate one.
    if completed_at is None:
        completed_at = datetime.now().isoformat()

    # Extract domain from the final result.
    domain = result.get("domain", "unknown")

    # --------------------------------------------------------
    # Build history snapshot
    # --------------------------------------------------------

    snapshot = {
        "history_version": 1,

        "scan_id": scan_id,

        "domain": domain,

        "started_at": started_at,

        "completed_at": completed_at,

        "saved_at": datetime.now().isoformat(),

        # Keep the complete DomainAtlas result.
        "result": _make_json_safe(result),
    }

    # --------------------------------------------------------
    # Calculate duration when timestamps are available
    # --------------------------------------------------------

    if started_at and completed_at:
        try:
            start_time = datetime.fromisoformat(started_at)
            end_time = datetime.fromisoformat(completed_at)

            duration = (
                end_time - start_time
            ).total_seconds()

            snapshot["duration_seconds"] = max(
                0,
                round(duration, 2)
            )

        except (ValueError, TypeError):
            snapshot["duration_seconds"] = None

    else:
        snapshot["duration_seconds"] = None

    # --------------------------------------------------------
    # Save JSON
    # --------------------------------------------------------

    file_path = _history_file(scan_id)

    with open(
        file_path,
        "w",
        encoding="utf-8",
    ) as history_file:

        json.dump(
            snapshot,
            history_file,
            indent=2,
            ensure_ascii=False,
        )

    print(
        f"[+] Scan history saved: {file_path}"
    )

    return {
        "scan_id": scan_id,
        "domain": domain,
        "completed_at": completed_at,
        "duration_seconds": snapshot[
            "duration_seconds"
        ],
        "file_path": str(file_path),
    }


# ============================================================
# LIST HISTORY
# ============================================================

def list_history() -> List[Dict[str, Any]]:
    """
    Return lightweight metadata for all saved scans.

    The complete scan results are NOT loaded here.
    This keeps the History page fast.
    """

    history_entries = []

    for file_path in HISTORY_DIR.glob(
        "scan_*.json"
    ):

        try:
            with open(
                file_path,
                "r",
                encoding="utf-8",
            ) as history_file:

                snapshot = json.load(
                    history_file
                )

            result = snapshot.get(
                "result",
                {}
            )

            graph_analysis = result.get(
                "graph_analysis",
                {}
            )

            infrastructure = (
                graph_analysis.get(
                    "infrastructure",
                    {}
                )
                if isinstance(
                    graph_analysis,
                    dict
                )
                else {}
            )

            # ------------------------------------------------
            # Basic counts for History cards
            # ------------------------------------------------

            subdomains = infrastructure.get(
                "subdomains",
                []
            )

            ip_addresses = infrastructure.get(
                "ip_addresses",
                []
            )

            asns = infrastructure.get(
                "asns",
                []
            )

            organizations = infrastructure.get(
                "organizations",
                []
            )

            certificates = infrastructure.get(
                "certificates",
                []
            )

            port_scan = result.get(
                "port_scan",
                {}
            )

            open_ports = []

            if isinstance(port_scan, dict):
                open_ports = port_scan.get(
                    "open_ports",
                    []
                )

            history_entries.append(
                {
                    "scan_id": snapshot.get(
                        "scan_id"
                    ),

                    "domain": snapshot.get(
                        "domain",
                        result.get(
                            "domain",
                            "unknown"
                        )
                    ),

                    "started_at": snapshot.get(
                        "started_at"
                    ),

                    "completed_at": snapshot.get(
                        "completed_at"
                    ),

                    "duration_seconds": snapshot.get(
                        "duration_seconds"
                    ),

                    "subdomains": len(
                        subdomains
                    ),

                    "ip_addresses": len(
                        ip_addresses
                    ),

                    "asns": len(
                        asns
                    ),

                    "organizations": len(
                        organizations
                    ),

                    "certificates": len(
                        certificates
                    ),

                    "open_ports": len(
                        open_ports
                    ),

                    "file_name": file_path.name,
                }
            )

        except (
            OSError,
            json.JSONDecodeError,
            TypeError,
            AttributeError,
        ) as error:

            print(
                f"[!] Could not read history file "
                f"{file_path.name}: {error}"
            )

    # Newest scans first.
    history_entries.sort(
        key=lambda item: (
            item.get("completed_at")
            or ""
        ),
        reverse=True,
    )

    return history_entries


# ============================================================
# GET SINGLE SCAN
# ============================================================

def get_scan(
    scan_id: str,
) -> Optional[Dict[str, Any]]:
    """
    Load a complete historical scan.

    Returns None if the scan does not exist.
    """

    file_path = _history_file(scan_id)

    if not file_path.exists():
        return None

    try:
        with open(
            file_path,
            "r",
            encoding="utf-8",
        ) as history_file:

            return json.load(
                history_file
            )

    except (
        OSError,
        json.JSONDecodeError,
    ) as error:

        print(
            f"[!] Could not load scan history "
            f"{scan_id}: {error}"
        )

        return None


# ============================================================
# DELETE SCAN
# ============================================================

def delete_scan(
    scan_id: str,
) -> bool:
    """
    Delete a historical scan.

    Returns True when deleted, False when
    the scan does not exist.
    """

    file_path = _history_file(scan_id)

    if not file_path.exists():
        return False

    try:
        file_path.unlink()

        print(
            f"[+] Deleted scan history: "
            f"{scan_id}"
        )

        return True

    except OSError as error:

        print(
            f"[!] Could not delete scan history "
            f"{scan_id}: {error}"
        )

        return False